In [ ]:
# Project: Car Sales Data Exploration

# Create a small custom DataFrame using your own data
# such as car names and colors.

# Perform basic analysis on important columns.
# For example, find average, highest, and lowest values.

# Create a simple plot to understand how values are distributed.
# A histogram of price is a good starting point.

# Add titles and labels to the plot so it is easy to understand.

# Save the cleaned dataset into a new CSV file.

# Write a short summary of what you did and what you observed.

In [1]:
# Import the libraries needed for working with data and creating plots.
import pandas as pd
import matplotlib as plt

In [2]:
# Load the dataset from a CSV file into a DataFrame.
car_sales_data = pd.read_csv("cars.csv")
car_sales_data

               Car   Color  Mileage  Doors    Price
0   Toyota Corolla   White    45000      4   850000
1       Honda City  Silver    32000      4   920000
2      Hyundai i20    Blue    28000      4   650000
3     Maruti Swift     Red    51000      4   550000
4  Mahindra XUV300   Black    22000      4  1150000
5       Tata Nexon    Grey    18000      4   980000
6       Kia Seltos   White    26000      4  1450000
7    Ford EcoSport    Blue    39000      4   780000
8     Renault Kwid     Red    30000      4   420000
9  Volkswagen Polo   Black    41000      4   690000

In [3]:
# Show the first few rows to get an idea of how the data looks.
car_sales_data.head()

               Car   Color  Mileage  Doors    Price
0   Toyota Corolla   White    45000      4   850000
1       Honda City  Silver    32000      4   920000
2      Hyundai i20    Blue    28000      4   650000
3     Maruti Swift     Red    51000      4   550000
4  Mahindra XUV300   Black    22000      4  1150000

In [4]:
# Look at column names, data types, and overall information.
car_sales_data.columns
car_sales_data.dtypes
car_sales_data.info

<bound method DataFrame.info of                Car   Color  Mileage  Doors    Price
0   Toyota Corolla   White    45000      4   850000
1       Honda City  Silver    32000      4   920000
2      Hyundai i20    Blue    28000      4   650000
3     Maruti Swift     Red    51000      4   550000
4  Mahindra XUV300   Black    22000      4  1150000
5       Tata Nexon    Grey    18000      4   980000
6       Kia Seltos   White    26000      4  1450000
7    Ford EcoSport    Blue    39000      4   780000
8     Renault Kwid     Red    30000      4   420000
9  Volkswagen Polo   Black    41000      4   690000>

In [5]:
# Generate a summary of numerical data.
# Observe values like average, minimum, and maximum.

car_sales_data.describe().info

<bound method DataFrame.info of             Mileage  Doors         Price
count     10.000000   10.0  1.000000e+01
mean   33200.000000    4.0  8.440000e+05
std    10528.268825    0.0  3.012640e+05
min    18000.000000    4.0  4.200000e+05
25%    26500.000000    4.0  6.600000e+05
50%    31000.000000    4.0  8.150000e+05
75%    40500.000000    4.0  9.650000e+05
max    51000.000000    4.0  1.450000e+06>

In [6]:
car_sales_data[["Price","Mileage"]].mean()
car_sales_data[["Price","Mileage"]].median()
car_sales_data[["Price","Mileage"]].mode()

     Price  Mileage
0   420000    18000
1   550000    22000
2   650000    26000
3   690000    28000
4   780000    30000
5   850000    32000
6   920000    39000
7   980000    41000
8  1150000    45000
9  1450000    51000

In [7]:
# Look for any unnecessary columns such as unnamed index columns
# and remove them if they are not useful.
car_sales_data.columns

Index(['Car', 'Color', 'Mileage', 'Doors', 'Price'], dtype='str')

In [8]:
# Check if there are any missing values in the dataset.
car_sales_data.isnull().any

<bound method DataFrame.any of      Car  Color  Mileage  Doors  Price
0  False  False    False  False  False
1  False  False    False  False  False
2  False  False    False  False  False
3  False  False    False  False  False
4  False  False    False  False  False
5  False  False    False  False  False
6  False  False    False  False  False
7  False  False    False  False  False
8  False  False    False  False  False
9  False  False    False  False  False>